# Generated by Django 5.1.3 on 2024-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafileimage",
            name="relation",
            field=models.BooleanField(
                blank=True, choices=[("film", "Фильм"), ("celebrity", "Звезда")], null=True, verbose_name="Категория"
            ),
        ),
    ]
