# Generated by Django 5.1.3 on 2024-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_info", "0003_alter_mediafileimage_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafileimage",
            name="relation",
            field=models.CharField(
                choices=[("film", "Фильм"), ("celebrity", "Звезда")], max_length=255, verbose_name="Категория"
            ),
        ),
    ]
